### ISSUE TITLE
vagrant provisionがこける

### ISSUE THREAD

**Issue by tyoshii** [tyoshii/bms#257]
@yuokada 出番です。

**Comment by tyoshii** [comment]
@yuokada このコメント、全くきづいてなかった・・・超今さらごめん

切り出しなしで、そのままでいいような気がするんだけど、
メリデメ何かあった？

**Comment by yuokada** [comment]
@tyoshii bmsとしてはvagrant使う必要はかならずしもないから分けてもいいんじゃないかと思った。
コミットログとか混じらないほうが本体の変更も追いやすいしそのあたりも分けるメリットかなって思う。

**Comment by yuokada** [comment]
＊ リポジトリ2つになるから管理の面では手間が増えるのでデメリット

**Comment by kseta** [comment]
@tyoshii @yuokada 
私も分けたほうがいいと思います。
アプリケーションの変更とインフラ構成の変更はそれぞれ独立したプロダクトとして進めたほうが見通しがよいと思います。

もし分けるのでしたら、別レポジトリを作成していただければそこで実装進めます。
（その際、レポジトリの名前は cookbook-bms などで空レポジトリを作って欲しいです。）

**Comment by tyoshii** [comment]
@yuokada @kseta なるほど。メリットのほうがおおそうなのでわけましょー

**Comment by tyoshii** [comment]
@kseta created https://github.com/tyoshii/cookbook-bms

**Comment by kseta** [comment]
@tyoshii ありがとうございます！

**Comment by yuokada** [comment]
既存のvagrant以下の履歴は消しても問題無いと思うので新しいリポジトリで1から始めるのがいいかと思います。

**Comment by kseta** [comment]
@yuokada 承知しました。

**Comment by kseta** [comment]
@tyoshii cookbook-bms に Initial commit として 空のREADMEファイルなどを作成してもらってもいいですか？ForkできないのでPRできなくて。

もしくは cookbook-bms の権限もらって直接レポジトリに Push していく感じでもOKです。

どちらかご対応お願いします。

**Comment by yuokada** [comment]
@kseta vagrantのリポジトリが動く状態になったらこっちのリポジトリのvagrant以下に改めてsubmoduleとしてとひもづけるのがいいですかね？

**Comment by kseta** [comment]
@yuokada 
そうですね！
あんまり submodule したことないので使い勝手は不明なのですが、現在の構成を維持するのであればそれがよいのではないかと思います。

**Comment by yuokada** [comment]
@kseta 了解です。

**Comment by tyoshii** [comment]
@kseta おまたせしてすみません。
initial commit done　です。
https://github.com/tyoshii/cookbook-bms

**Comment by tyoshii** [comment]
@kseta @yuokada 二人のコラボレーターへの追加もDone

**Comment by tyoshii** [comment]
https://github.com/tyoshii/cookbook-bms
こっちでやるのでissue close
