### ISSUE TITLE
メールの開封確認機能

### ISSUE THREAD

**Issue by yuokada** [tyoshii/bms#402]
- [ ] 開封確認用のビーコンを埋め込み
- [ ] ログをスキャンして開封されたことを確認するcron or daemonの開発
- [ ] 管理画面へ開封されたことを通知するUIの追加

成績入ってない人に簡単にリマインド出せればいいはずなので手段としては大げさだと思う。
余裕ある時に遊びで作れればやれればいいかな。

**Comment by tyoshii** [comment]
一旦クローズ
