### ISSUE TITLE
ユーザーと選手名の考え方

### ISSUE THREAD

**Issue by tyoshii** [tyoshii/bms#427]
### いま

* ユーザーは複数のチームに登録できる。
* 登録チームごとに、選手名を変更できる
    * レジャーズの吉井　と　フォトクリエイトの助っ人A
    * （どちらもログインIDはtyoshii）

### 変更後

* ユーザーは複数のチームに登録できる。
* 自分の選手名は1つだけ、全てのチームで共通の名前を使う
   * レジャーズの吉井　は　フォトクリエイトでも吉井

何か違和感あります？
@yuokada @shonuma @kseta

**Comment by shonuma** [comment]
リーグ、チームに紐づく情報が存在しているのであれば、問題ないと思います。
以下の成績がそれぞれ確認できればOK
- レジャーズの吉井
- フォトクリエイトの吉井
- ITリーグ関連試合の吉井

**Comment by yuokada** [comment]
@tyoshii そもそもなんで現仕様になってるか不明ですが変更後の仕様については違和感無いです。

**Comment by tyoshii** [comment]
整理出来ましたありがとうございました。
