### ISSUE TITLE
長野テンプレートからのインサート機能

### ISSUE THREAD

**Issue by tyoshii** [tyoshii/bms#436]

**Comment by tyoshii** [comment]
テンプレートあとであげます

**Comment by tyoshii** [comment]
@shonuma おｋ？

**Comment by tyoshii** [comment]
[【18_Yahoo_2012】.xls | uploaded via ZenHub](https://files.zenhub.io/54d6125c0109b8b05b2dae32)

**Comment by tyoshii** [comment]
@shonuma 長野さんが管理してる成績のデータはこれです。

言語得意なやつでいいので、パース処理お願いします。

**Comment by tyoshii** [comment]
リポジトリ分けたほうがいいかなと思ったり

**Comment by tyoshii** [comment]
どう思う？

**Comment by tyoshii** [comment]
シートがいくつかわかれているけど、

* 1枚のExcelでアップロードして、シートごとにぱーすできる？
* CSVにしてもらって各々アップロードしてもらった方がいい？

悩みますね。

**Comment by tyoshii** [comment]
@shonuma are you ok ?

**Comment by shonuma** [comment]
見ました！すみません。確認させていただきますを

**Comment by tyoshii** [comment]
@shonuma thx!!

https://github.com/tyoshii/bms/wiki/%E3%83%87%E3%83%BC%E3%82%BF%E3%83%86%E3%83%BC%E3%83%96%E3%83%AB%E8%A8%AD%E8%A8%88
ER図もあります。

（成績チェックするAPIの実装で、テーブル少し変更ありそうなので、updateしておきます）

**Comment by shonuma** [comment]
ER図みました。凄いことになっていた…

**Comment by shonuma** [comment]
これは、確かにリポジトリ分けたほうがいいかもしれないですね。

**Comment by shonuma** [comment]
### ER図
 - https://cloud.githubusercontent.com/assets/427856/6094505/da9f1fa2-af6f-11e4-84b0-0584e26dcaf6.png

### CSVだとシート毎にしかできない模様
 - シート毎にCSVにしてもらってアップロード？
 - マクロならできるやつがあるらしい
   - http://excel-magic.com/post-24/
   - ちょっと微妙かも

**Comment by shonuma** [comment]
とりあえず命名規則を
 - [チーム名]{dageki,senshu,shiai,toushu}{stat,""}{db}
にする
```
MBP-15UAC-010:bms sonuma$ ls [*
[18_Yahoo_2012]dagekidb.csv	[18_Yahoo_2012]senshudb.csv	[18_Yahoo_2012]toushudb.csv
[18_Yahoo_2012]dagekistatdb.csv	[18_Yahoo_2012]shiaidb.csv	[18_Yahoo_2012]toushustatdb.csv
```

**Comment by kseta** [comment]
> ER図

:+1:

**Comment by shonuma** [comment]
ExcelシートをLinuxで読める形のTSV(CSV)に変換する
```
cat ../18_Yahoo_2012-toushu-statdb.txt | iconv -f sjis -t utf8 | tr $'\x0d' $'\n'
```

**Comment by tyoshii** [comment]
@shonuma リポジトリそのままでもいいし、きったほうがいい、とかあれば、取り急ぎshonumaの下に切ってもらえると助かる。

**Comment by tyoshii** [comment]
（organization とろうとおもったら bms はすでに取られていて死）

**Comment by tyoshii** [comment]
シート別にアップロードしてもらうのはいいのだけど、ちょっとそれだとややこしいきがするのだが、ぬまっちちょっと相談しよう

**Comment by shonuma** [comment]
打撃DB、投手DBのデータがアップロードされた時、
与えられたデータをparseして、以下のテーブルにinsertする用のSQLを組み立てる。

https://cloud.githubusercontent.com/assets/427856/6094505/da9f1fa2-af6f-11e4-84b0-0584e26dcaf6.png
```
stats_hittings
stats_pitchings
stats_hittingdetails
```

**Comment by shonuma** [comment]
hittingdetailsについて、方向とかN打席目の値は0にしてよい。

**Comment by tyoshii** [comment]
たち消えたとおもうので、一旦クローズ
